In [1]:
%load_ext autoreload
%autoreload 2

import pandas as pd 
import numpy as np
import openpyxl
import re
import warnings
from src.config import DATA_RAW, DATA_PROCESSED
from IPython.display import display
from src.preprocessing import clean_sponsor_columns
from src.data_loader import load_raw, save_processed, load_processed
from src.preprocessing import clean_data, check_missing_values, check_duplicates, clean_sponsor_columns, clean_region_column
warnings.filterwarnings("ignore")
pd.set_option('display.max_columns', None)
pd.options.display.float_format = '{:.2f}'.format

In [2]:
df_dirty = load_raw('Turan_oyun günü sorğusu.xlsx')
df = df_dirty.copy()
df.columns = df.columns.str.strip()
df.columns = df.columns.str.replace(r'\s+', ' ', regex=True).str.strip()
df.head()

'Turan_oyun günü sorğusu.xlsx' Excel faylı kimi oxundu. Shape: (52, 49)

,Timestamp,Turan Tovuz PFK-nın oyunlarını hansı tezlikdə izləyirsiniz?,Hansı səbəbdən oyunları tez tez izləmirsiniz?,Oyunları əsasən necə izləyirsiniz?,Oyunları hansı səbəbdən stadionda izləmirsiniz?,Oyun barədə məlumatı haradan əldə etmisiniz?,Bileti haradan almısınız?,Stadiona getmək üçün hansı vasitədən istifadə etmisiniz?,Stadionda son izlədiyiniz oyunu sizinlə neçə nəfər gəlib?,"Stadionda son izlədiyiniz oyunu sizinlə gələnlərin arasında uşaq var idi? bir neçə uşaq gəlmişdirsə, sayı ""digər"" bölməsində qeyd edə bilərsiniz","Sizcə, oyuna ailənizlə gəlmək üçün şərait uyğundurmu?",Xahiş edirik stadiona gedərkən üzləşdiyiniz problemləri qeyd edin:,Xahiş edirik stadionda üzləşdiyiniz problemləri qeyd edin:,Xahiş edirik stadiondan çıxarkən üzləşdiyiniz problemləri qeyd edin:,Stadion ərazisində satışda olan qida və içkilər almısınızmı?,Oyun zamanı satışda olan qida və içkilərə ortalama nə qədər pul xərcləmisiniz? məbləğ(AZN),Satış məntəqələrinin əlçatan olması,Qida və içkilərin çeşidləri,Qida və içkilərin keyfiyyəti,Qida və içkilərin qiyməti,Stadion ərazisindəki fanşopdan klubun məhsullarını almısınızmı?,Oyun zamanı satışda olan klubun məhsullarına nə qədər pul xərcləmisiniz?,Satış məntəqələrinin əlçatan olması 2,Məhsulların çeşidləri,Məhsulların keyfiyyəti,Bilet alma prosesini necə qiymətləndirirsiniz?,Bilet yoxlayan əməkdaşların işini necə qiymətləndirirsiniz?,Təhlükəsizlik xidmətinin işini necə qiymətləndirirsiniz?,"Könüllülərin işini necə qiymətləndirirsiniz? (istiqamətin göstərilməsi, sualların cavablandırılması və s.)",Tribunaların təmizliyini necə qiymətləndirirsiniz?,Tualetlərin təmizliyini necə qiymətləndirirsiniz?,Stadionda olan ab-havanı necə qiymətləndirirsiniz?,Ümumi oyunun təşkilini necə qiymətləndirirsiniz?,Klubun faəliyyətini necə dəyərləndirirsiniz?,Sponsorun dəstəyini necə dəyərləndirirsiniz?,Stadionda neçə sponsor reklamı gördünüz?,Bunlar hansılardır?,"Son oyundakı təcrübənizə əsasən, Turan Tovuz PFK-nın növbəti oyunlarını stadionda izləmək istəyərdiniz?","Son oyundakı təcrübənizə əsasən, dostlarınıza Turan Tovuz PFK-nın oyunlarını stadionda izləməyi tövsiyə edərsiniz?","Ad, soyad",Cins,Yaşınız,Məşğuliyyət,Ailə vəziyyəti,Turan Tovuz PFK-nın fəaliyyəti ilə bağlı məlumat almaq istəyirsinizmi?,Qeydlər,"Harada yaşayırsınız, oyunu izləməyə haradan gəlmisiniz? rayon/kəndin adını qeyd edin",Məhsulların qiyməti,Column 46
0,2025-03-19 15:47:08.896,Hər oyununu izləyirəm,NaN,Stadionda baxıram,NaN,Sosial media kanallarından,Stadionun kassasından,Piyada,2,Xeyr,Bəli,Qarşı tribunanın üstünün bağlı olması,Heç bir problemlə üzləşmədim,Heç bir problemlə üzləşmədim,Bəli,1,10.00,5.00,5.00,5.00,Xeyr,NaN,NaN,NaN,NaN,10,7,10,9,10,10.00,10,6,10,10,1,huner group,Bəli,Bəli,Tural İmanov,Kişi,37,İşləyirəm,Evli,Bəli,NaN,Tovuz şəhəri,NaN,NaN
1,2025-03-18 12:57:01.184,Hər oyununu izləyirəm,NaN,Stadionda baxıram,NaN,Şəhərdə yerləşən posterlərdən,Stadionun kassasından,Piyada,12,Xeyr,Bəli,Heç bir problemlə üzləşmədim,Heç bir problemlə üzləşmədim,Heç bir problemlə üzləşmədim,Bəli,1,10.00,10.00,10.00,10.00,Xeyr,NaN,NaN,NaN,NaN,10,10,10,10,10,10.00,10,10,10,10,3,hg/tovuz su/FİF,Bəli,Bəli,Rüstəm Zeynalov,Kişi,42,İşsizəm,Evli,Bəli,NaN,NaN,NaN,NaN
2,2025-03-18 12:07:38.943,Hər oyununu izləyirəm,NaN,Stadionda baxıram,NaN,Tanışlardan,Dəvətnamə veriblər,Taksi,1,Bəli,Bəli,"Stadionun parkinqində yerin az olması, Heç bir...",Tütün məhsullarının istifadəsi. Smiçka çırtdam...,"Stadiondan çıxış zamanı sıxlıq olması, Heç bir...",Bəli,1,8.00,5.00,7.00,5.00,Bəli,10,8.00,5.00,8.00,10,10,10,10,10,5.00,10,10,8,10,3,"huner group, oyal, böyük qışlaq su",Bəli,Bəli,Gülnarə Qədirova,Qadın,33,İşsizəm,Evli,Xeyr,Yaşasın Tovuz,NaN,NaN,NaN
3,2025-03-19 14:06:35.732,Hər oyununu izləyirəm,NaN,Stadionda baxıram,NaN,Sosial media kanallarından,Stadionun kassasından,İctimai nəqliyyat,8,Bəli,Bəli,Heç bir problemlə üzləşmədim,Heç bir problemlə üzləşmədim,Heç bir problemlə üzləşmədim,Bəli,2,1.00,8.00,10.00,3.00,Bəli,2,10.00,10.00,10.00,10,10,10,10,10,10.00,10,10,10,10,1,Huner qurup,Bəli,Bəli,Sameddin qumasov,Kişi,34,USTA,Evli,Bəli,NISALLAH TURUN KULUBUNU AVROPADA GORUM.,Tovuz R.N Azafli kend,10.00,NaN
4,2025-03-17 20:44:32.298,Hər oyununu izləyirəm,NaN,Stadionda baxıram,NaN,Sosial media kanallarından,Səyyar satış məntəqəsindən,Şəxsi avtomobil,1,Bəli,Bəli,Heç bir problemlə üzləşmədim,qadın tualetinden kşilərin istifadə etməsi,Heç bir problemlə üzləşmədim,Bəli,2,10.00,10.00,10.00,3.00,Bəli,5,10.00,10.00,10.00,10,10,8,8,10,9.00,10,10,9,10,"huner group, ada store",2,Bəli,Bəli,Rəşad Şrinov,Kişi,45,İşləyirəm,Evli,Bəli,NaN,NaN,NaN,NaN

In [3]:
df.columns = (
    df.columns
    .str.replace(r'\s+', ' ', regex=True) 
    .str.strip() 
    .str.replace(r'\s+([?.,!])', r'\1', regex=True)  
)

In [4]:
info_df = pd.DataFrame({
    'Column': [col[:30] + '...' if len(col) > 30 else col for col in df.columns],
    'Dtype': df.dtypes.values,
    'Non-Null Count': df.notnull().sum().values
})

print(info_df.to_string())

                               Column           Dtype  Non-Null Count
0                           Timestamp  datetime64[us]              52
1   Turan Tovuz PFK-nın oyunlarını...             str              52
2   Hansı səbəbdən oyunları tez te...             str               5
3   Oyunları əsasən necə izləyirsi...             str              51
4   Oyunları hansı səbəbdən stadio...             str               9
5   Oyun barədə məlumatı haradan ə...             str              52
6           Bileti haradan almısınız?             str              52
7   Stadiona getmək üçün hansı vas...             str              52
8   Stadionda son izlədiyiniz oyun...          object              52
9   Stadionda son izlədiyiniz oyun...          object              52
10  Sizcə, oyuna ailənizlə gəlmək ...             str              52
11  Xahiş edirik stadiona gedərkən...             str              52
12  Xahiş edirik stadionda üzləşdi...             str              52
13  Xahiş edirik stadiondan çıxark...             str              52
14  Stadion ərazisində satışda ola...             str              52
15  Oyun zamanı satışda olan qida ...          object              29
16  Satış məntəqələrinin əlçatan o...         float64              29
17        Qida və içkilərin çeşidləri         float64              29
18       Qida və içkilərin keyfiyyəti         float64              29
19          Qida və içkilərin qiyməti         float64              29
20  Stadion ərazisindəki fanşopdan...             str              52
21  Oyun zamanı satışda olan klubu...          object               9
22  Satış məntəqələrinin əlçatan o...         float64               9
23              Məhsulların çeşidləri         float64               9
24             Məhsulların keyfiyyəti         float64               9
25  Bilet alma prosesini necə qiym...           int64              52
26  Bilet yoxlayan əməkdaşların iş...           int64              52
27  Təhlükəsizlik xidmətinin işini...           int64              52
28  Könüllülərin işini necə qiymət...           int64              52
29  Tribunaların təmizliyini necə ...           int64              52
30  Tualetlərin təmizliyini necə q...         float64              51
31  Stadionda olan ab-havanı necə ...           int64              52
32  Ümumi oyunun təşkilini necə qi...           int64              52
33  Klubun faəliyyətini necə dəyər...           int64              52
34  Sponsorun dəstəyini necə dəyər...           int64              52
35  Stadionda neçə sponsor reklamı...          object              52
36                Bunlar hansılardır?          object              52
37  Son oyundakı təcrübənizə əsasə...             str              52
38  Son oyundakı təcrübənizə əsasə...             str              52
39                          Ad, soyad             str              52
40                               Cins             str              52
41                            Yaşınız          object              52
42                        Məşğuliyyət             str              52
43                     Ailə vəziyyəti             str              52
44  Turan Tovuz PFK-nın fəaliyyəti...             str              52
45                            Qeydlər             str              17
46  Harada yaşayırsınız, oyunu izl...             str              37
47                Məhsulların qiyməti         float64               4
48                          Column 46         float64               0

In [5]:
df.describe()

,Timestamp,Satış məntəqələrinin əlçatan olması,Qida və içkilərin çeşidləri,Qida və içkilərin keyfiyyəti,Qida və içkilərin qiyməti,Satış məntəqələrinin əlçatan olması 2,Məhsulların çeşidləri,Məhsulların keyfiyyəti,Bilet alma prosesini necə qiymətləndirirsiniz?,Bilet yoxlayan əməkdaşların işini necə qiymətləndirirsiniz?,Təhlükəsizlik xidmətinin işini necə qiymətləndirirsiniz?,"Könüllülərin işini necə qiymətləndirirsiniz? (istiqamətin göstərilməsi, sualların cavablandırılması və s.)",Tribunaların təmizliyini necə qiymətləndirirsiniz?,Tualetlərin təmizliyini necə qiymətləndirirsiniz?,Stadionda olan ab-havanı necə qiymətləndirirsiniz?,Ümumi oyunun təşkilini necə qiymətləndirirsiniz?,Klubun faəliyyətini necə dəyərləndirirsiniz?,Sponsorun dəstəyini necə dəyərləndirirsiniz?,Məhsulların qiyməti,Column 46
count,52,29.00,29.00,29.00,29.00,9.00,9.00,9.00,52.00,52.00,52.00,52.00,52.00,51.00,52.00,52.00,52.00,52.00,4.00,0.00
mean,2025-03-18 21:51:51.605365,8.00,7.59,8.03,6.34,8.89,7.67,9.11,8.98,8.69,9.06,8.58,8.50,7.92,9.44,8.42,8.33,9.35,8.25,NaN
min,2025-03-17 19:51:21.764000,1.00,3.00,1.00,1.00,5.00,3.00,6.00,3.00,3.00,5.00,1.00,1.00,1.00,3.00,3.00,3.00,3.00,5.00,NaN
25%,2025-03-18 12:52:02.381500,7.00,6.00,7.00,5.00,8.00,5.00,8.00,8.00,8.00,8.00,8.00,8.00,6.00,10.00,7.75,7.00,10.00,7.25,NaN
50%,2025-03-18 14:27:20.239000,8.00,8.00,9.00,6.00,10.00,10.00,10.00,10.00,9.50,10.00,10.00,10.00,9.00,10.00,9.00,9.00,10.00,9.00,NaN
75%,2025-03-19 11:49:31.846250,10.00,10.00,10.00,8.00,10.00,10.00,10.00,10.00,10.00,10.00,10.00,10.00,10.00,10.00,10.00,10.00,10.00,10.00,NaN
max,2025-03-24 20:58:29.613000,10.00,10.00,10.00,10.00,10.00,10.00,10.00,10.00,10.00,10.00,10.00,10.00,10.00,10.00,10.00,10.00,10.00,10.00,NaN
std,NaN,2.28,2.15,2.29,2.72,1.83,2.87,1.45,1.58,1.81,1.30,2.40,2.42,2.27,1.43,1.74,1.93,1.52,2.36,NaN

In [6]:
check_duplicates(df)

np.int64(0)

In [7]:
check_missing_values(df).head(17)

                                                    missing_values
Column 46                                                       52
Məhsulların qiyməti                                             48
Hansı səbəbdən oyunları tez tez izləmirsiniz?                   47
Oyunları hansı səbəbdən stadionda izləmirsiniz?                 43
Məhsulların keyfiyyəti                                          43
Məhsulların çeşidləri                                           43
Satış məntəqələrinin əlçatan olması 2                           43
Oyun zamanı satışda olan klubun məhsullarına nə...              43
Qeydlər                                                         35
Qida və içkilərin keyfiyyəti                                    23
Satış məntəqələrinin əlçatan olması                             23
Oyun zamanı satışda olan qida və içkilərə ortal...              23
Qida və içkilərin çeşidləri                                     23
Qida və içkilərin qiyməti                                       23
Harada yaşayırsınız, oyunu izləməyə haradan gəl...              15
Tualetlərin təmizliyini necə qiymətləndirirsiniz?                1
Oyunları əsasən necə izləyirsiniz?                               1

In [8]:
df.columns = df.columns.str.strip()  # boşluqları at
df.columns = df.columns.str.replace('\n', ' ')  # sətir daxilində \n varsa

In [9]:
df = df.drop(columns=['Column 46'])

In [10]:
df['Stadion ərazisindəki fanşopdan klubun məhsullarını almısınızmı?'].value_counts(dropna=False)

Stadion ərazisindəki fanşopdan klubun məhsullarını almısınızmı?
Xeyr    43
Bəli     9
Name: count, dtype: int64

In [11]:
df['Məhsulların qiyməti'].value_counts(dropna=False)

Məhsulların qiyməti
NaN      48
10.00     2
8.00      1
5.00      1
Name: count, dtype: int64

In [12]:
null_columns = df.columns[df.isnull().any()].tolist()

for col in null_columns:
    print(f"Column: {col}")
    print(df[col].value_counts(dropna=False))
    print("\n")

Column: Hansı səbəbdən oyunları tez tez izləmirsiniz?
Hansı səbəbdən oyunları tez tez izləmirsiniz?
NaN                               47
İzləməyə vaxtım yoxdur             2
Futbolçular zəifdir                1
Oyunlar barədə məlumatım olmur     1
futbola marağ yoxdu                1
Name: count, dtype: int64


Column: Oyunları əsasən necə izləyirsiniz?
Oyunları əsasən necə izləyirsiniz?
Stadionda baxıram              44
Onlayn izləyirəm                4
Evdə, televizorda izləyirəm     3
NaN                             1
Name: count, dtype: int64


Column: Oyunları hansı səbəbdən stadionda izləmirsiniz?
Oyunları hansı səbəbdən stadionda izləmirsiniz?
NaN                                           43
Stadiona getməyə vaxtım olmur                  2
Stadionda izləməyi sevmirəm                    2
Stadiona getməyə vaxtım olmur, İşdə oluram     1
Komandanının zəifliyinə görə                   1
bakı da qalıram                                1
Stadion uzaq yerləşdiyinə görə,                1
Çox vaxt bakıda olur                           1
Name: count, dtype: int64


Column: Oyun zamanı satışda olan qida və içkilərə ortalama nə qədər pul xərcləmisiniz? məbləğ(AZN)
Oyun zamanı satışda olan qida və içkilərə ortalama nə qədər pul xərcləmisiniz? məbləğ(AZN)
NaN               23
1                  3
2                  3
5                  3
10                 3
6                  2
20                 2
4                  1
7                  1
15                 1
18                 1
10 AZN             1
10 manata kimi     1
3-4                1
5-6                1
5-6man             1
5manat             1
7-8                1
7-dən çox          1
8 manat            1
Name: count, dtype: int64


Column: Satış məntəqələrinin əlçatan olması
Satış məntəqələrinin əlçatan olması
NaN      23
10.00    12
8.00      5
5.00      4
7.00      3
9.00      2
6.00      2
1.00      1
Name: count, dtype: int64


Column: Qida və içkilərin çeşidləri
Qida və içkilərin çeşidləri
NaN      23
10.00     9
5.00      6
7.00      4
8.00      3
6.00      3
9.00      3
3.00      1
Name: count, dtype: int64


Column: Qida və içkilərin keyfiyyəti
Qida və içkilərin keyfiyyəti
NaN      23
10.00    11
9.00      6
5.00      4
7.00      4
6.00      2
8.00      1
1.00      1
Name: count, dtype: int64


Column: Qida və içkilərin qiyməti
Qida və içkilərin qiyməti
NaN      23
5.00      5
10.00     5
8.00      4
6.00      4
7.00      3
3.00      2
9.00      2
1.00      2
4.00      1
2.00      1
Name: count, dtype: int64


Column: Oyun zamanı satışda olan klubun məhsullarına nə qədər pul xərcləmisiniz?
Oyun zamanı satışda olan klubun məhsullarına nə qədər pul xərcləmisiniz?
NaN         43
5            2
10           1
2            1
45           1
30man        1
85 manat     1
40           1
Forma        1
Name: count, dtype: int64


Column: Satış məntəqələrinin əlçatan olması 2
Satış məntəqələrinin əlçatan olması 2
NaN      43
10.00     6
8.00      1
7.00      1
5.00      1
Name: count, dtype: int64


Column: Məhsulların çeşidləri
Məhsulların çeşidləri
NaN      43
10.00     5
5.00      2
6.00      1
3.00      1
Name: count, dtype: int64


Column: Məhsulların keyfiyyəti
Məhsulların keyfiyyəti
NaN      43
10.00     6
8.00      2
6.00      1
Name: count, dtype: int64


Column: Tualetlərin təmizliyini necə qiymətləndirirsiniz?
Tualetlərin təmizliyini necə qiymətləndirirsiniz?
10.00    20
5.00      9
9.00      6
8.00      6
7.00      5
6.00      3
NaN       1
3.00      1
1.00      1
Name: count, dtype: int64


Column: Qeydlər
Qeydlər
NaN                                                                                                                                      35
Yaşasın Tovuz                                                                                                                             1
NISALLAH TURUN KULUBUNU AVROPADA GORUM.                                                                                                   1
Suni ot örtüyü təbii ot örtüyü ilə əvəzlənsə əla olar                                                                                     1
Şəhid qardaşıdı                                                                                                                           1
Avropaya getsinlər satdion ot örtüyü təbii olsun                                                                                          1
Oyunçuları dəyişik.                                                                                                                       1
Sponsor reklamları sayını dəqiqləşdir                                                                                                     1
                                                                                                                                          1
Mikrafonu düzəltmək kalonkalarını düzəltmək.                                                                                              1
Komandamıza uğurlar arzu edirem\n                                                                                                         1
Yoxdu                                                                                                                                     1
Klub hücum futbolu oynamır. qol vuru müdafiədə oturu                                                                                      1
Sadəc oyunlarını düzəltsinlər düzgün oyunasınlar. Qələbə lazımdı                                                                          1
Güclü komandayla yaxşı oynayır zəyif komandalara uduzur. Arashı bəyənmirəm deyir yaxşı oyunçu deyil. Ot örtüyünü dəyişlsə yaxşı olar.     1
Ailə üçün xüsusi vip olsa yaxşı olar ailəmizdə gələ bilər                                                                                 1
Hakim haksızlığı. Çəkliş pisdi deyir. Hakim haksızlığı var Turan Tovuza                                                                   1
Zədəlilər qayıtsa avropaya getmək istəyir.Turan Tovuza görə nəvəsinə Turan adı qoyub                                                      1
Name: count, dtype: int64


Column: Harada yaşayırsınız, oyunu izləməyə haradan gəlmisiniz? rayon/kəndin adını qeyd edin
Harada yaşayırsınız, oyunu izləməyə haradan gəlmisiniz? rayon/kəndin adını qeyd edin
NaN                             15
Şəhərin özündə                   4
Tovuz r                          2
Tovuz şəhəri                     1
Tovuz R.N Azafli kend            1
Düz cırdaxan kəndi               1
Əlimərdanlı                      1
Cəlilli                          1
Qovlar                           1
Köhnə qala - Tovuzun kəndi       1
tovuz r                          1
Alakol                           1
tovuz rayonu                     1
Tovuz Şəhərinin özündən          1
Tovuz r_n duz cirdaxan kəndi     1
Aşağı quşçu                      1
Aşğıqulşu                        1
Bakı                             1
bozalqanlı                       1
bozaqanlı                        1
əsrik çırdaxan                   1
Əsrik kəndi                      1
Əyyublu kəndində qalır           1
Kənd                             1
Qovullar                         1
Qozaqanlı                        1
Tovuz                            1
Tovuz                            1
tovuz                            1
Tovuz özündə                     1
Tovuz özündən                    1
tovuz ş                          1
Tovuz Şəhəri                     1
Xatınlı kəndinə                  1
Name: count, dtype: int64


Column: Məhsulların qiyməti
Məhsulların qiyməti
NaN      48
10.00     2
8.00      1
5.00      1
Name: count, dtype: int64

In [13]:
def parse_money(value):
    if pd.isna(value):
        return None  # NaN olaraq qalır (sual aid deyildi)
    
    value = str(value).strip().lower()
    
    # "forma" kimi qeyri-pul cavabları — ayrıca qeyd üçün saxla, rəqəmə çevirmə
    if not re.search(r'\d', value):
        return None
    
    # Aralıq varsa (3-4, 5-6), ortasını götür
    range_match = re.match(r'(\d+)\s*-\s*(\d+)', value)
    if range_match:
        low, high = map(int, range_match.groups())
        return (low + high) / 2
    
    # "7-dən çox" kimi aşağı sərhəd
    if 'çox' in value:
        num = re.search(r'\d+', value)
        return int(num.group()) + 1 if num else None  # təxmini
    
    # Sadə rəqəm (mətnlə qarışıq: "10 AZN", "5manat")
    num_match = re.search(r'\d+', value)
    return int(num_match.group()) if num_match else None

df['Oyun zamanı satışda olan qida və içkilərə ortalama nə qədər pul xərcləmisiniz? məbləğ(AZN)'] = df['Oyun zamanı satışda olan qida və içkilərə ortalama nə qədər pul xərcləmisiniz? məbləğ(AZN)'].apply(parse_money)
df['Oyun zamanı satışda olan klubun məhsullarına nə qədər pul xərcləmisiniz?'] = df['Oyun zamanı satışda olan klubun məhsullarına nə qədər pul xərcləmisiniz?'].apply(parse_money)

In [14]:
#Araşdırılan məlumata əsasən oyuna baxmağa gəlmişdir
df['Oyunları əsasən necə izləyirsiniz?'] = df['Oyunları əsasən necə izləyirsiniz?'].fillna('Stadionda baxıram')

In [15]:
conditional_fill = {
    'Hansı səbəbdən oyunları tez tez izləmirsiniz?': 'Qeyd olunmayıb',
    'Oyunları hansı səbəbdən stadionda izləmirsiniz?': 'Qeyd olunmayıb',
}
for col, val in conditional_fill.items():
    df[col] = df[col].fillna(val)

# 3. Könüllü mətn sualları
df['Harada yaşayırsınız, oyunu izləməyə haradan gəlmisiniz? rayon/kəndin adını qeyd edin'] = \
    df['Harada yaşayırsınız, oyunu izləməyə haradan gəlmisiniz? rayon/kəndin adını qeyd edin'].fillna('Qeyd olunmayıb')


# 4. Qeydlər — əvvəlcə boşluq-string-ləri təmizlə, sonra doldur
df['Qeydlər'] = df['Qeydlər'].replace(r'^\s*$', pd.NA, regex=True)
df['Qeydlər'] = df['Qeydlər'].fillna('Şərh yoxdur')

print("Qalan NaN sayı:\n", df.isnull().sum()[df.isnull().sum() > 0])

Qalan NaN sayı:
 Oyun zamanı satışda olan qida və içkilərə ortalama nə qədər pul xərcləmisiniz? məbləğ(AZN)    23
Satış məntəqələrinin əlçatan olması                                                           23
Qida və içkilərin çeşidləri                                                                   23
Qida və içkilərin keyfiyyəti                                                                  23
Qida və içkilərin qiyməti                                                                     23
Oyun zamanı satışda olan klubun məhsullarına nə qədər pul xərcləmisiniz?                      44
Satış məntəqələrinin əlçatan olması 2                                                         43
Məhsulların çeşidləri                                                                         43
Məhsulların keyfiyyəti                                                                        43
Tualetlərin təmizliyini necə qiymətləndirirsiniz?                                              1
Məhsulların qiyməti                                                                           48
dtype: int64

In [16]:
df[df['Oyunları əsasən necə izləyirsiniz?'] == "Stadionda baxıram"].shape[0]

45

In [17]:
df['Bunlar hansılardır?'].value_counts(dropna=False)

Bunlar hansılardır?
huner group                                        11
0                                                   7
Hünər Qrup                                          5
Hünər qrup                                          3
2                                                   2
huner group                                         2
Huner Group                                         2
hg/tovuz su/FİF                                     1
huner group, oyal, böyük qışlaq su                  1
Huner qurup                                         1
Hünər Qrup Tovuz su və digərləri                    1
huner                                               1
taniks/az group/hüner group/kapital bank plakat     1
Hüner group/tovuz mall                              1
yadında deyil                                       1
Huner group, Tovuz Mall                             1
Tovuz su. Hünər qurup. Racism. Misli. Pfl. az       1
Böyük qışlaq suyu hauder                            1
huner, tovuz su,                                    1
Hünər Grup                                          1
Hünər Qrup və digər                                 1
Tovuz su,Hünər Qrup                                 1
huner group,                                        1
Hünər Qurup                                         1
Hüner Qrup                                          1
Tovuz Su Hünər Qrup                                 1
Görmədim                                            1
Name: count, dtype: int64

In [18]:
df = clean_sponsor_columns(df)

In [19]:
df.head()

,Timestamp,Turan Tovuz PFK-nın oyunlarını hansı tezlikdə izləyirsiniz?,Hansı səbəbdən oyunları tez tez izləmirsiniz?,Oyunları əsasən necə izləyirsiniz?,Oyunları hansı səbəbdən stadionda izləmirsiniz?,Oyun barədə məlumatı haradan əldə etmisiniz?,Bileti haradan almısınız?,Stadiona getmək üçün hansı vasitədən istifadə etmisiniz?,Stadionda son izlədiyiniz oyunu sizinlə neçə nəfər gəlib?,"Stadionda son izlədiyiniz oyunu sizinlə gələnlərin arasında uşaq var idi? bir neçə uşaq gəlmişdirsə, sayı ""digər"" bölməsində qeyd edə bilərsiniz","Sizcə, oyuna ailənizlə gəlmək üçün şərait uyğundurmu?",Xahiş edirik stadiona gedərkən üzləşdiyiniz problemləri qeyd edin:,Xahiş edirik stadionda üzləşdiyiniz problemləri qeyd edin:,Xahiş edirik stadiondan çıxarkən üzləşdiyiniz problemləri qeyd edin:,Stadion ərazisində satışda olan qida və içkilər almısınızmı?,Oyun zamanı satışda olan qida və içkilərə ortalama nə qədər pul xərcləmisiniz? məbləğ(AZN),Satış məntəqələrinin əlçatan olması,Qida və içkilərin çeşidləri,Qida və içkilərin keyfiyyəti,Qida və içkilərin qiyməti,Stadion ərazisindəki fanşopdan klubun məhsullarını almısınızmı?,Oyun zamanı satışda olan klubun məhsullarına nə qədər pul xərcləmisiniz?,Satış məntəqələrinin əlçatan olması 2,Məhsulların çeşidləri,Məhsulların keyfiyyəti,Bilet alma prosesini necə qiymətləndirirsiniz?,Bilet yoxlayan əməkdaşların işini necə qiymətləndirirsiniz?,Təhlükəsizlik xidmətinin işini necə qiymətləndirirsiniz?,"Könüllülərin işini necə qiymətləndirirsiniz? (istiqamətin göstərilməsi, sualların cavablandırılması və s.)",Tribunaların təmizliyini necə qiymətləndirirsiniz?,Tualetlərin təmizliyini necə qiymətləndirirsiniz?,Stadionda olan ab-havanı necə qiymətləndirirsiniz?,Ümumi oyunun təşkilini necə qiymətləndirirsiniz?,Klubun faəliyyətini necə dəyərləndirirsiniz?,Sponsorun dəstəyini necə dəyərləndirirsiniz?,Stadionda neçə sponsor reklamı gördünüz?,Bunlar hansılardır?,"Son oyundakı təcrübənizə əsasən, Turan Tovuz PFK-nın növbəti oyunlarını stadionda izləmək istəyərdiniz?","Son oyundakı təcrübənizə əsasən, dostlarınıza Turan Tovuz PFK-nın oyunlarını stadionda izləməyi tövsiyə edərsiniz?","Ad, soyad",Cins,Yaşınız,Məşğuliyyət,Ailə vəziyyəti,Turan Tovuz PFK-nın fəaliyyəti ilə bağlı məlumat almaq istəyirsinizmi?,Qeydlər,"Harada yaşayırsınız, oyunu izləməyə haradan gəlmisiniz? rayon/kəndin adını qeyd edin",Məhsulların qiyməti
0,2025-03-19 15:47:08.896,Hər oyununu izləyirəm,Qeyd olunmayıb,Stadionda baxıram,Qeyd olunmayıb,Sosial media kanallarından,Stadionun kassasından,Piyada,2,Xeyr,Bəli,Qarşı tribunanın üstünün bağlı olması,Heç bir problemlə üzləşmədim,Heç bir problemlə üzləşmədim,Bəli,1.00,10.00,5.00,5.00,5.00,Xeyr,NaN,NaN,NaN,NaN,10,7,10,9,10,10.00,10,6,10,10,1,HUNER GROUP,Bəli,Bəli,Tural İmanov,Kişi,37,İşləyirəm,Evli,Bəli,Şərh yoxdur,Tovuz şəhəri,NaN
1,2025-03-18 12:57:01.184,Hər oyununu izləyirəm,Qeyd olunmayıb,Stadionda baxıram,Qeyd olunmayıb,Şəhərdə yerləşən posterlərdən,Stadionun kassasından,Piyada,12,Xeyr,Bəli,Heç bir problemlə üzləşmədim,Heç bir problemlə üzləşmədim,Heç bir problemlə üzləşmədim,Bəli,1.00,10.00,10.00,10.00,10.00,Xeyr,NaN,NaN,NaN,NaN,10,10,10,10,10,10.00,10,10,10,10,3,"HUNER GROUP, Tovuz Su, FİF",Bəli,Bəli,Rüstəm Zeynalov,Kişi,42,İşsizəm,Evli,Bəli,Şərh yoxdur,Qeyd olunmayıb,NaN
2,2025-03-18 12:07:38.943,Hər oyununu izləyirəm,Qeyd olunmayıb,Stadionda baxıram,Qeyd olunmayıb,Tanışlardan,Dəvətnamə veriblər,Taksi,1,Bəli,Bəli,"Stadionun parkinqində yerin az olması, Heç bir...",Tütün məhsullarının istifadəsi. Smiçka çırtdam...,"Stadiondan çıxış zamanı sıxlıq olması, Heç bir...",Bəli,1.00,8.00,5.00,7.00,5.00,Bəli,10.00,8.00,5.00,8.00,10,10,10,10,10,5.00,10,10,8,10,3,"HUNER GROUP, Oyal, Böyük Qışlaq Su",Bəli,Bəli,Gülnarə Qədirova,Qadın,33,İşsizəm,Evli,Xeyr,Yaşasın Tovuz,Qeyd olunmayıb,NaN
3,2025-03-19 14:06:35.732,Hər oyununu izləyirəm,Qeyd olunmayıb,Stadionda baxıram,Qeyd olunmayıb,Sosial media kanallarından,Stadionun kassasından,İctimai nəqliyyat,8,Bəli,Bəli,Heç bir problemlə üzləşmədim,Heç bir problemlə üzləşmədim,Heç bir problemlə üzləşmədim,Bəli,2.00,1.00,8.00,10.00,3.00,Bəli,2.00,10.00,10.00,10.00,10,10,10,10,10,10.00,10,10,10,10,1,HUNER GROUP,Bəli,Bəli,Sameddin qumasov,Kişi,34,USTA,Evli,Bəli,NISALLAH TURUN KULUBUNU AVROPADA GORUM.,Tovuz R.N Azafli kend,10.00
4,2025-03-17 20:44:32.298,Hər oyununu izləyirəm,Qeyd olunmayıb,Stadionda baxıram,Qeyd olunmayıb,Sosial media kanallarından,Səyyar satış məntəqəsindən,Şəxsi avtomobil,1,Bəli,Bəli,Heç bir problemlə üzləşmədim,qadın tualetinden kşilərin istifadə etməsi,Heç bir problemlə üzləşmədim,Bəli,2.00,10.00,10.00,10.00,3.00,Bəli,5.00,10.00,10.00,10.00,10,10,8,8,10,9.00,10,10,9,10,2,"HUNER GROUP, Ada Store",Bəli,Bəli,Rəşad Şrinov,Kişi,45,İşləyirəm,Evli,Bəli,Şərh yoxdur,Qeyd olunmayıb,NaN

In [20]:
df.shape

(52, 48)

In [21]:
df = clean_sponsor_columns(df)

df['Bunlar hansılardır?'].value_counts(dropna=False)

Bunlar hansılardır?
HUNER GROUP                                   29
NaN                                           11
Tovuz Su, HUNER GROUP                          3
HUNER GROUP, Tovuz Su                          2
HUNER GROUP, Tovuz Mall                        2
HUNER GROUP, Tovuz Su, FİF                     1
HUNER GROUP, Oyal, Böyük Qışlaq Su             1
HUNER GROUP, Ada Store                         1
Az Group, HUNER GROUP, Kapital Bank Plakat     1
Böyük Qışlaq Su                                1
Name: count, dtype: int64

In [22]:
df['Bunlar hansılardır?'] = df['Bunlar hansılardır?'].astype(str).str.strip().replace(['görmədim', 'yadında deyil'], np.nan)
df['Bunlar hansılardır?'] = df['Bunlar hansılardır?'].astype(str).str.strip().replace(r'^2$', 'HUNER GROUP, Ada Store', regex=True)

In [23]:
df['Bunlar hansılardır?'] = df['Bunlar hansılardır?'].astype(str).str.strip().replace(['hünər qurup', 'hüner qrup', 'hünər grup','HUNER GROUP,', 'huner', 'hünər qrup'], 'HUNER GROUP')

In [24]:
df['Bunlar hansılardır?'].value_counts(dropna=False)

Bunlar hansılardır?
HUNER GROUP                                   29
NaN                                           11
Tovuz Su, HUNER GROUP                          3
HUNER GROUP, Tovuz Su                          2
HUNER GROUP, Tovuz Mall                        2
HUNER GROUP, Tovuz Su, FİF                     1
HUNER GROUP, Oyal, Böyük Qışlaq Su             1
HUNER GROUP, Ada Store                         1
Az Group, HUNER GROUP, Kapital Bank Plakat     1
Böyük Qışlaq Su                                1
Name: count, dtype: int64

In [25]:
df['Stadionda neçə sponsor reklamı gördünüz?'].value_counts(dropna=False)

Stadionda neçə sponsor reklamı gördünüz?
1    30
0    11
2     8
3     3
Name: count, dtype: int64

In [26]:
df['Stadionda neçə sponsor reklamı gördünüz?'].apply(pd.to_numeric, errors='coerce')
df['Stadionda neçə sponsor reklamı gördünüz?'] = df['Stadionda neçə sponsor reklamı gördünüz?'].astype('Int64')

In [27]:
df.head()

,Timestamp,Turan Tovuz PFK-nın oyunlarını hansı tezlikdə izləyirsiniz?,Hansı səbəbdən oyunları tez tez izləmirsiniz?,Oyunları əsasən necə izləyirsiniz?,Oyunları hansı səbəbdən stadionda izləmirsiniz?,Oyun barədə məlumatı haradan əldə etmisiniz?,Bileti haradan almısınız?,Stadiona getmək üçün hansı vasitədən istifadə etmisiniz?,Stadionda son izlədiyiniz oyunu sizinlə neçə nəfər gəlib?,"Stadionda son izlədiyiniz oyunu sizinlə gələnlərin arasında uşaq var idi? bir neçə uşaq gəlmişdirsə, sayı ""digər"" bölməsində qeyd edə bilərsiniz","Sizcə, oyuna ailənizlə gəlmək üçün şərait uyğundurmu?",Xahiş edirik stadiona gedərkən üzləşdiyiniz problemləri qeyd edin:,Xahiş edirik stadionda üzləşdiyiniz problemləri qeyd edin:,Xahiş edirik stadiondan çıxarkən üzləşdiyiniz problemləri qeyd edin:,Stadion ərazisində satışda olan qida və içkilər almısınızmı?,Oyun zamanı satışda olan qida və içkilərə ortalama nə qədər pul xərcləmisiniz? məbləğ(AZN),Satış məntəqələrinin əlçatan olması,Qida və içkilərin çeşidləri,Qida və içkilərin keyfiyyəti,Qida və içkilərin qiyməti,Stadion ərazisindəki fanşopdan klubun məhsullarını almısınızmı?,Oyun zamanı satışda olan klubun məhsullarına nə qədər pul xərcləmisiniz?,Satış məntəqələrinin əlçatan olması 2,Məhsulların çeşidləri,Məhsulların keyfiyyəti,Bilet alma prosesini necə qiymətləndirirsiniz?,Bilet yoxlayan əməkdaşların işini necə qiymətləndirirsiniz?,Təhlükəsizlik xidmətinin işini necə qiymətləndirirsiniz?,"Könüllülərin işini necə qiymətləndirirsiniz? (istiqamətin göstərilməsi, sualların cavablandırılması və s.)",Tribunaların təmizliyini necə qiymətləndirirsiniz?,Tualetlərin təmizliyini necə qiymətləndirirsiniz?,Stadionda olan ab-havanı necə qiymətləndirirsiniz?,Ümumi oyunun təşkilini necə qiymətləndirirsiniz?,Klubun faəliyyətini necə dəyərləndirirsiniz?,Sponsorun dəstəyini necə dəyərləndirirsiniz?,Stadionda neçə sponsor reklamı gördünüz?,Bunlar hansılardır?,"Son oyundakı təcrübənizə əsasən, Turan Tovuz PFK-nın növbəti oyunlarını stadionda izləmək istəyərdiniz?","Son oyundakı təcrübənizə əsasən, dostlarınıza Turan Tovuz PFK-nın oyunlarını stadionda izləməyi tövsiyə edərsiniz?","Ad, soyad",Cins,Yaşınız,Məşğuliyyət,Ailə vəziyyəti,Turan Tovuz PFK-nın fəaliyyəti ilə bağlı məlumat almaq istəyirsinizmi?,Qeydlər,"Harada yaşayırsınız, oyunu izləməyə haradan gəlmisiniz? rayon/kəndin adını qeyd edin",Məhsulların qiyməti
0,2025-03-19 15:47:08.896,Hər oyununu izləyirəm,Qeyd olunmayıb,Stadionda baxıram,Qeyd olunmayıb,Sosial media kanallarından,Stadionun kassasından,Piyada,2,Xeyr,Bəli,Qarşı tribunanın üstünün bağlı olması,Heç bir problemlə üzləşmədim,Heç bir problemlə üzləşmədim,Bəli,1.00,10.00,5.00,5.00,5.00,Xeyr,NaN,NaN,NaN,NaN,10,7,10,9,10,10.00,10,6,10,10,1,HUNER GROUP,Bəli,Bəli,Tural İmanov,Kişi,37,İşləyirəm,Evli,Bəli,Şərh yoxdur,Tovuz şəhəri,NaN
1,2025-03-18 12:57:01.184,Hər oyununu izləyirəm,Qeyd olunmayıb,Stadionda baxıram,Qeyd olunmayıb,Şəhərdə yerləşən posterlərdən,Stadionun kassasından,Piyada,12,Xeyr,Bəli,Heç bir problemlə üzləşmədim,Heç bir problemlə üzləşmədim,Heç bir problemlə üzləşmədim,Bəli,1.00,10.00,10.00,10.00,10.00,Xeyr,NaN,NaN,NaN,NaN,10,10,10,10,10,10.00,10,10,10,10,3,"HUNER GROUP, Tovuz Su, FİF",Bəli,Bəli,Rüstəm Zeynalov,Kişi,42,İşsizəm,Evli,Bəli,Şərh yoxdur,Qeyd olunmayıb,NaN
2,2025-03-18 12:07:38.943,Hər oyununu izləyirəm,Qeyd olunmayıb,Stadionda baxıram,Qeyd olunmayıb,Tanışlardan,Dəvətnamə veriblər,Taksi,1,Bəli,Bəli,"Stadionun parkinqində yerin az olması, Heç bir...",Tütün məhsullarının istifadəsi. Smiçka çırtdam...,"Stadiondan çıxış zamanı sıxlıq olması, Heç bir...",Bəli,1.00,8.00,5.00,7.00,5.00,Bəli,10.00,8.00,5.00,8.00,10,10,10,10,10,5.00,10,10,8,10,3,"HUNER GROUP, Oyal, Böyük Qışlaq Su",Bəli,Bəli,Gülnarə Qədirova,Qadın,33,İşsizəm,Evli,Xeyr,Yaşasın Tovuz,Qeyd olunmayıb,NaN
3,2025-03-19 14:06:35.732,Hər oyununu izləyirəm,Qeyd olunmayıb,Stadionda baxıram,Qeyd olunmayıb,Sosial media kanallarından,Stadionun kassasından,İctimai nəqliyyat,8,Bəli,Bəli,Heç bir problemlə üzləşmədim,Heç bir problemlə üzləşmədim,Heç bir problemlə üzləşmədim,Bəli,2.00,1.00,8.00,10.00,3.00,Bəli,2.00,10.00,10.00,10.00,10,10,10,10,10,10.00,10,10,10,10,1,HUNER GROUP,Bəli,Bəli,Sameddin qumasov,Kişi,34,USTA,Evli,Bəli,NISALLAH TURUN KULUBUNU AVROPADA GORUM.,Tovuz R.N Azafli kend,10.00
4,2025-03-17 20:44:32.298,Hər oyununu izləyirəm,Qeyd olunmayıb,Stadionda baxıram,Qeyd olunmayıb,Sosial media kanallarından,Səyyar satış məntəqəsindən,Şəxsi avtomobil,1,Bəli,Bəli,Heç bir problemlə üzləşmədim,qadın tualetinden kşilərin istifadə etməsi,Heç bir problemlə üzləşmədim,Bəli,2.00,10.00,10.00,10.00,3.00,Bəli,5.00,10.00,10.00,10.00,10,10,8,8,10,9.00,10,10,9,10,2,"HUNER GROUP, Ada Store",Bəli,Bəli,Rəşad Şrinov,Kişi,45,İşləyirəm,Evli,Bəli,Şərh yoxdur,Qeyd olunmayıb,NaN

---------

In [28]:
# Burada 40 yazmışam, çünki 1985 martın 14 tarixində doğulmuş şəxs 2025-ci ildə 40 yaşındadır
# və 34 yazmağımın səbəbi isə Hüseynov Əsgər adlı şəxsin digər məlumat datasına əsasən 34 yaşında olmasıdır
df['Yaşınız'] = df['Yaşınız'].astype(str).str.strip().replace('1985 martın 14', 40)
df['Yaşınız'] = df['Yaşınız'].astype(str).str.strip().replace('Tovuz', 34)

In [29]:
df['Yaşınız'] = pd.to_numeric(df['Yaşınız'], errors='coerce').astype('Int64')

---------

In [30]:
df['Stadionda son izlədiyiniz oyunu sizinlə gələnlərin arasında uşaq var idi? bir neçə uşaq gəlmişdirsə, sayı "digər" bölməsində qeyd edə bilərsiniz'] = \
    df['Stadionda son izlədiyiniz oyunu sizinlə gələnlərin arasında uşaq var idi? bir neçə uşaq gəlmişdirsə, sayı "digər" bölməsində qeyd edə bilərsiniz'].astype(str).str.strip().replace(['Dostunun qızı ilə', '3 / 1 oğ 2 qiz', '2'], 'Bəli')

-----

In [31]:
df['Stadionda son izlədiyiniz oyunu sizinlə neçə nəfər gəlib?'] = df['Stadionda son izlədiyiniz oyunu sizinlə neçə nəfər gəlib?'].astype(str).str.strip().replace(['3-4'], 3)
df['Stadionda son izlədiyiniz oyunu sizinlə neçə nəfər gəlib?'] = df['Stadionda son izlədiyiniz oyunu sizinlə neçə nəfər gəlib?'].astype(str).str.strip().replace(['Tək gəlmişəm'], 0)
df['Stadionda son izlədiyiniz oyunu sizinlə neçə nəfər gəlib?'] = df['Stadionda son izlədiyiniz oyunu sizinlə neçə nəfər gəlib?'].astype(str).str.strip().replace(['10+'], 10)
df['Stadionda son izlədiyiniz oyunu sizinlə neçə nəfər gəlib?'] = df['Stadionda son izlədiyiniz oyunu sizinlə neçə nəfər gəlib?'].astype(str).str.strip().replace(['2 Oğul ilə gəlib'], 2)
df['Stadionda son izlədiyiniz oyunu sizinlə neçə nəfər gəlib?'] = df['Stadionda son izlədiyiniz oyunu sizinlə neçə nəfər gəlib?'].astype(str).str.strip().replace(['Dostları ilə'], 3)

In [32]:
df['Stadionda son izlədiyiniz oyunu sizinlə neçə nəfər gəlib?'] = df['Stadionda son izlədiyiniz oyunu sizinlə neçə nəfər gəlib?'].apply(pd.to_numeric, errors='coerce')
df['Stadionda son izlədiyiniz oyunu sizinlə neçə nəfər gəlib?'] = df['Stadionda son izlədiyiniz oyunu sizinlə neçə nəfər gəlib?'].astype('Int64')

-------

In [33]:
df['Sizcə, oyuna ailənizlə gəlmək üçün şərait uyğundurmu?'] = df['Sizcə, oyuna ailənizlə gəlmək üçün şərait uyğundurmu?'].astype(str).str.strip().replace(['50 faiz', 'Ailəli yer olsun yaxşı olar', 'Ancaq uşaqlarla gəlməyə uygundur', 'Bəzi yerlərdə bəli vip', 'Xüsusi zona olsa gəlmək olar'], 'Qismən').replace(['Söyüş söyülməsi', 'çox bərbaddı. natəmizlik , söüş, semiçka', 'Söyüş çox söyülür ailə üçün xüsusi yer yoxdu', 'Söüşün söyülməsi', 'Ailə ilə gəlmək olmur söyüş söyülür.'], 'Xeyr').replace(['he'], 'Bəli')

In [34]:
df['Sizcə, oyuna ailənizlə gəlmək üçün şərait uyğundurmu?'].value_counts(dropna=False)

Sizcə, oyuna ailənizlə gəlmək üçün şərait uyğundurmu?
Bəli      26
Xeyr      21
Qismən     5
Name: count, dtype: int64

In [35]:
df['Oyun zamanı satışda olan qida və içkilərə ortalama nə qədər pul xərcləmisiniz? məbləğ(AZN)'].value_counts

<bound method IndexOpsMixin.value_counts of 0     1.00
1     1.00
2     1.00
3     2.00
4     2.00
5     2.00
6     4.00
7     5.00
8     5.00
9     5.00
10    6.00
11    6.00
12    7.00
13   10.00
14   10.00
15   10.00
16   15.00
17   18.00
18   20.00
19   20.00
20   10.00
21   10.00
22    3.50
23    5.50
24    5.50
25    5.00
26    7.50
27    8.00
28    8.00
29     NaN
30     NaN
31     NaN
32     NaN
33     NaN
34     NaN
35     NaN
36     NaN
37     NaN
38     NaN
39     NaN
40     NaN
41     NaN
42     NaN
43     NaN
44     NaN
45     NaN
46     NaN
47     NaN
48     NaN
49     NaN
50     NaN
51     NaN
Name: Oyun zamanı satışda olan qida və içkilərə ortalama nə qədər pul xərcləmisiniz? məbləğ(AZN), dtype: float64>

In [36]:
df['Harada yaşayırsınız, oyunu izləməyə haradan gəlmisiniz? rayon/kəndin adını qeyd edin'].value_counts(dropna=False)

Harada yaşayırsınız, oyunu izləməyə haradan gəlmisiniz? rayon/kəndin adını qeyd edin
Qeyd olunmayıb                  15
Şəhərin özündə                   4
Tovuz r                          2
Tovuz şəhəri                     1
Tovuz R.N Azafli kend            1
Düz cırdaxan kəndi               1
Əlimərdanlı                      1
Cəlilli                          1
Qovlar                           1
Köhnə qala - Tovuzun kəndi       1
tovuz r                          1
Alakol                           1
tovuz rayonu                     1
Tovuz Şəhərinin özündən          1
Tovuz r_n duz cirdaxan kəndi     1
Aşağı quşçu                      1
Aşğıqulşu                        1
Bakı                             1
bozalqanlı                       1
bozaqanlı                        1
əsrik çırdaxan                   1
Əsrik kəndi                      1
Əyyublu kəndində qalır           1
Kənd                             1
Qovullar                         1
Qozaqanlı                        1
Tovuz                            1
Tovuz                            1
tovuz                            1
Tovuz özündə                     1
Tovuz özündən                    1
tovuz ş                          1
Tovuz Şəhəri                     1
Xatınlı kəndinə                  1
Name: count, dtype: int64

In [37]:
df['Harada yaşayırsınız, oyunu izləməyə haradan gəlmisiniz? rayon/kəndin adını qeyd edin'] = df['Harada yaşayırsınız, oyunu izləməyə haradan gəlmisiniz? rayon/kəndin adını qeyd edin'].astype(str).str.strip().replace(['Əyyublu kəndində qalır'], 'Əyyublu kəndi')
df['Harada yaşayırsınız, oyunu izləməyə haradan gəlmisiniz? rayon/kəndin adını qeyd edin'] = df['Harada yaşayırsınız, oyunu izləməyə haradan gəlmisiniz? rayon/kəndin adını qeyd edin'].astype(str).str.strip().replace(['Kənd'], 'Aşağı Quşçu kəndi')

In [38]:
df = clean_region_column(df)
df.head(2)

Diqqət: aşağıdakı dəyərlər heç bir kənd/şəhər şablonuna uyğun gəlmədi və olduğu kimi saxlanıldı (əl ilə yoxlayın):
  - Qeyd olunmayıb
  - Əyyublu kəndi

,Timestamp,Turan Tovuz PFK-nın oyunlarını hansı tezlikdə izləyirsiniz?,Hansı səbəbdən oyunları tez tez izləmirsiniz?,Oyunları əsasən necə izləyirsiniz?,Oyunları hansı səbəbdən stadionda izləmirsiniz?,Oyun barədə məlumatı haradan əldə etmisiniz?,Bileti haradan almısınız?,Stadiona getmək üçün hansı vasitədən istifadə etmisiniz?,Stadionda son izlədiyiniz oyunu sizinlə neçə nəfər gəlib?,"Stadionda son izlədiyiniz oyunu sizinlə gələnlərin arasında uşaq var idi? bir neçə uşaq gəlmişdirsə, sayı ""digər"" bölməsində qeyd edə bilərsiniz","Sizcə, oyuna ailənizlə gəlmək üçün şərait uyğundurmu?",Xahiş edirik stadiona gedərkən üzləşdiyiniz problemləri qeyd edin:,Xahiş edirik stadionda üzləşdiyiniz problemləri qeyd edin:,Xahiş edirik stadiondan çıxarkən üzləşdiyiniz problemləri qeyd edin:,Stadion ərazisində satışda olan qida və içkilər almısınızmı?,Oyun zamanı satışda olan qida və içkilərə ortalama nə qədər pul xərcləmisiniz? məbləğ(AZN),Satış məntəqələrinin əlçatan olması,Qida və içkilərin çeşidləri,Qida və içkilərin keyfiyyəti,Qida və içkilərin qiyməti,Stadion ərazisindəki fanşopdan klubun məhsullarını almısınızmı?,Oyun zamanı satışda olan klubun məhsullarına nə qədər pul xərcləmisiniz?,Satış məntəqələrinin əlçatan olması 2,Məhsulların çeşidləri,Məhsulların keyfiyyəti,Bilet alma prosesini necə qiymətləndirirsiniz?,Bilet yoxlayan əməkdaşların işini necə qiymətləndirirsiniz?,Təhlükəsizlik xidmətinin işini necə qiymətləndirirsiniz?,"Könüllülərin işini necə qiymətləndirirsiniz? (istiqamətin göstərilməsi, sualların cavablandırılması və s.)",Tribunaların təmizliyini necə qiymətləndirirsiniz?,Tualetlərin təmizliyini necə qiymətləndirirsiniz?,Stadionda olan ab-havanı necə qiymətləndirirsiniz?,Ümumi oyunun təşkilini necə qiymətləndirirsiniz?,Klubun faəliyyətini necə dəyərləndirirsiniz?,Sponsorun dəstəyini necə dəyərləndirirsiniz?,Stadionda neçə sponsor reklamı gördünüz?,Bunlar hansılardır?,"Son oyundakı təcrübənizə əsasən, Turan Tovuz PFK-nın növbəti oyunlarını stadionda izləmək istəyərdiniz?","Son oyundakı təcrübənizə əsasən, dostlarınıza Turan Tovuz PFK-nın oyunlarını stadionda izləməyi tövsiyə edərsiniz?","Ad, soyad",Cins,Yaşınız,Məşğuliyyət,Ailə vəziyyəti,Turan Tovuz PFK-nın fəaliyyəti ilə bağlı məlumat almaq istəyirsinizmi?,Qeydlər,"Harada yaşayırsınız, oyunu izləməyə haradan gəlmisiniz? rayon/kəndin adını qeyd edin",Məhsulların qiyməti
0,2025-03-19 15:47:08.896,Hər oyununu izləyirəm,Qeyd olunmayıb,Stadionda baxıram,Qeyd olunmayıb,Sosial media kanallarından,Stadionun kassasından,Piyada,2,Xeyr,Bəli,Qarşı tribunanın üstünün bağlı olması,Heç bir problemlə üzləşmədim,Heç bir problemlə üzləşmədim,Bəli,1.00,10.00,5.00,5.00,5.00,Xeyr,NaN,NaN,NaN,NaN,10,7,10,9,10,10.00,10,6,10,10,1,HUNER GROUP,Bəli,Bəli,Tural İmanov,Kişi,37,İşləyirəm,Evli,Bəli,Şərh yoxdur,Tovuz şəhəri,NaN
1,2025-03-18 12:57:01.184,Hər oyununu izləyirəm,Qeyd olunmayıb,Stadionda baxıram,Qeyd olunmayıb,Şəhərdə yerləşən posterlərdən,Stadionun kassasından,Piyada,12,Xeyr,Bəli,Heç bir problemlə üzləşmədim,Heç bir problemlə üzləşmədim,Heç bir problemlə üzləşmədim,Bəli,1.00,10.00,10.00,10.00,10.00,Xeyr,NaN,NaN,NaN,NaN,10,10,10,10,10,10.00,10,10,10,10,3,"HUNER GROUP, Tovuz Su, FİF",Bəli,Bəli,Rüstəm Zeynalov,Kişi,42,İşsizəm,Evli,Bəli,Şərh yoxdur,Qeyd olunmayıb,NaN

In [39]:
null_columns = df.columns[df.isnull().any()].tolist()

for col in df.columns:
    print(f"Column: {col}")
    print(df[col].dtype)
    print(df[col].value_counts(dropna=False))
    print("\n")

Column: Timestamp
datetime64[us]
Timestamp
2025-03-19 15:47:08.896    1
2025-03-18 12:57:01.184    1
2025-03-18 12:07:38.943    1
2025-03-19 14:06:35.732    1
2025-03-17 20:44:32.298    1
2025-03-18 12:46:55.111    1
2025-03-18 14:54:26.549    1
2025-03-18 13:46:38.504    1
2025-03-19 15:32:44.205    1
2025-03-17 20:02:28.512    1
2025-03-18 14:06:11.826    1
2025-03-19 11:55:36.203    1
2025-03-18 14:39:40.470    1
2025-03-18 13:55:34.562    1
2025-03-18 16:28:49.937    1
2025-03-18 12:33:41.752    1
2025-03-18 12:13:15.059    1
2025-03-19 12:20:37.727    1
2025-03-18 16:46:29.588    1
2025-03-18 12:16:27.531    1
2025-03-18 13:35:45.410    1
2025-03-18 12:53:44.805    1
2025-03-17 19:51:21.764    1
2025-03-18 14:50:58.885    1
2025-03-19 21:23:00.569    1
2025-03-24 20:58:29.613    1
2025-03-17 20:21:52.390    1
2025-03-18 12:41:43.087    1
2025-03-18 12:14:12.843    1
2025-03-19 11:31:33.868    1
2025-03-19 12:10:48.106    1
2025-03-18 17:14:43.878    1
2025-03-19 15:49:28.734    1
2025-03-18 16:52:15.572    1
2025-03-19 15:28:12.118    1
2025-03-18 16:39:54.236    1
2025-03-18 13:36:33.909    1
2025-03-18 17:02:24.019    1
2025-03-19 12:14:04.675    1
2025-03-18 14:23:23.752    1
2025-03-18 14:31:16.726    1
2025-03-18 15:06:38.239    1
2025-03-18 13:38:33.242    1
2025-03-18 13:53:41.806    1
2025-03-18 14:16:36.876    1
2025-03-18 14:12:25.467    1
2025-03-19 15:07:10.598    1
2025-03-19 15:08:39.700    1
2025-03-19 11:47:30.394    1
2025-03-18 14:00:07.404    1
2025-03-18 12:45:45.457    1
2025-03-17 20:31:10.748    1
Name: count, dtype: int64


Column: Turan Tovuz PFK-nın oyunlarını hansı tezlikdə izləyirsiniz?
str
Turan Tovuz PFK-nın oyunlarını hansı tezlikdə izləyirsiniz?
Hər oyununu izləyirəm       46
Nadir izləyirəm              5
Əksər oyunları izləyirəm     1
Name: count, dtype: int64


Column: Hansı səbəbdən oyunları tez tez izləmirsiniz?
str
Hansı səbəbdən oyunları tez tez izləmirsiniz?
Qeyd olunmayıb                    47
İzləməyə vaxtım yoxdur             2
Futbolçular zəifdir                1
Oyunlar barədə məlumatım olmur     1
futbola marağ yoxdu                1
Name: count, dtype: int64


Column: Oyunları əsasən necə izləyirsiniz?
str
Oyunları əsasən necə izləyirsiniz?
Stadionda baxıram              45
Onlayn izləyirəm                4
Evdə, televizorda izləyirəm     3
Name: count, dtype: int64


Column: Oyunları hansı səbəbdən stadionda izləmirsiniz?
str
Oyunları hansı səbəbdən stadionda izləmirsiniz?
Qeyd olunmayıb                                43
Stadiona getməyə vaxtım olmur                  2
Stadionda izləməyi sevmirəm                    2
Stadiona getməyə vaxtım olmur, İşdə oluram     1
Komandanının zəifliyinə görə                   1
bakı da qalıram                                1
Stadion uzaq yerləşdiyinə görə,                1
Çox vaxt bakıda olur                           1
Name: count, dtype: int64


Column: Oyun barədə məlumatı haradan əldə etmisiniz?
str
Oyun barədə məlumatı haradan əldə etmisiniz?
Sosial media kanallarından       34
Tanışlardan                      14
Şəhərdə yerləşən posterlərdən     3
Livescore proqram                 1
Name: count, dtype: int64


Column: Bileti haradan almısınız?
str
Bileti haradan almısınız?
Stadionun kassasından                       38
Dəvətnamə veriblər                           4
Stadionun girişindən                         4
Səyyar satış məntəqəsindən                   2
Qaziyəm                                      1
Bilet alınmır                                1
Biletlər Kamran                              1
Şəhərin mərkəzindəki satış məntəqəsindən     1
Name: count, dtype: int64


Column: Stadiona getmək üçün hansı vasitədən istifadə etmisiniz?
str
Stadiona getmək üçün hansı vasitədən istifadə etmisiniz?
Şəxsi avtomobil      26
Piyada               12
Taksi                 7
İctimai nəqliyyat     7
Name: count, dtype: int64


Column: Stadionda son izlədiyiniz oyunu sizinlə neçə nəfər gəlib?
Int64
Stadionda son izlədiyiniz oyunu sizinlə neçə nəfər gəlib?
3     11
5     10
2      9
4      7
1      4
6      3
0      2
10     2
12     1
8      1
7      1
15     1
Name: count, dtype: Int64


Column: Stadionda son izlədiyiniz oyunu sizinlə gələnlərin arasında uşaq var idi? bir neçə uşaq gəlmişdirsə, sayı "digər" bölməsində qeyd edə bilərsiniz
str
Stadionda son izlədiyiniz oyunu sizinlə gələnlərin arasında uşaq var idi? bir neçə uşaq gəlmişdirsə, sayı "digər" bölməsində qeyd edə bilərsiniz
Bəli    29
Xeyr    23
Name: count, dtype: int64


Column: Sizcə, oyuna ailənizlə gəlmək üçün şərait uyğundurmu?
str
Sizcə, oyuna ailənizlə gəlmək üçün şərait uyğundurmu?
Bəli      26
Xeyr      21
Qismən     5
Name: count, dtype: int64


Column: Xahiş edirik stadiona gedərkən üzləşdiyiniz problemləri qeyd edin:
str
Xahiş edirik stadiona gedərkən üzləşdiyiniz problemləri qeyd edin:
Heç bir problemlə üzləşmədim                                                                    39
Stadionun parkinqində yerin az olması                                                            5
Stadiona çatmaq üçün sərf olunan vaxtın çox, yolun isə uzun olması                               2
Qarşı tribunanın üstünün bağlı olması                                                            1
Stadionun parkinqində yerin az olması, Heç bir problemlə üzləşmədim                              1
Stadiona giriş zamanı sıraların çox olması (vaxt itkisi), butulkaların qapagının açıq olması     1
Söyüş söyülür                                                                                    1
Heç bir problemlə üzləşmədim,                                                                    1
Stadiona giriş zamanı sıraların çox olması (vaxt itkisi)                                         1
Name: count, dtype: int64


Column: Xahiş edirik stadionda üzləşdiyiniz problemləri qeyd edin:
str
Xahiş edirik stadionda üzləşdiyiniz problemləri qeyd edin:
Heç bir problemlə üzləşmədim                                              36
Oturacağım çirkli olması, Tualetlərin çirkli olması                        3
Oturacağım çirkli olması                                                   3
Tütün məhsullarının istifadəsi. Smiçka çırtdamaları                        1
qadın tualetinden kşilərin istifadə etməsi                                 1
Oturacağım çirkli olması, oturacaqlarda çuxolun olması                     1
Oruc tuturuq suların qapağını açılmağı                                     1
Tütün, söyüş                                                               1
Biletimdə göstərilən yerdə başqası oturmuşdu, Oturacağım çirkli olması     1
tütün istifadəsi                                                           1
Biletimdə göstərilən yerdə başqası oturmuşdu                               1
Söyüş söyülür                                                              1
Stadiona giriş də bilet yoxlayanın az olması                               1
Name: count, dtype: int64


Column: Xahiş edirik stadiondan çıxarkən üzləşdiyiniz problemləri qeyd edin:
str
Xahiş edirik stadiondan çıxarkən üzləşdiyiniz problemləri qeyd edin:
Heç bir problemlə üzləşmədim                                           39
Stadiondan çıxış zamanı sıxlıq olması                                   5
Avtomobil tıxacları                                                     3
Stadiondan çıxış zamanı sıxlıq olması, Heç bir problemlə üzləşmədim     1
birinci time çıxanda qapının bağlı olması                               1
Stadiondan çıxış zamanı sıxlıq olması, Avtomobil tıxacları              1
Maşın saxlamaq olmur polislər qoymur. Gəlir çərimə yazır                1
Söyüş söyülür                                                           1
Name: count, dtype: int64


Column: Stadion ərazisində satışda olan qida və içkilər almısınızmı?
str
Stadion ərazisində satışda olan qida və içkilər almısınızmı?
Bəli    29
Xeyr    23
Name: count, dtype: int64


Column: Oyun zamanı satışda olan qida və içkilərə ortalama nə qədər pul xərcləmisiniz? məbləğ(AZN)
float64
Oyun zamanı satışda olan qida və içkilərə ortalama nə qədər pul xərcləmisiniz? məbləğ(AZN)
NaN      23
10.00     5
5.00      4
1.00      3
2.00      3
6.00      2
20.00     2
5.50      2
8.00      2
4.00      1
7.00      1
15.00     1
18.00     1
3.50      1
7.50      1
Name: count, dtype: int64


Column: Satış məntəqələrinin əlçatan olması
float64
Satış məntəqələrinin əlçatan olması
NaN      23
10.00    12
8.00      5
5.00      4
7.00      3
9.00      2
6.00      2
1.00      1
Name: count, dtype: int64


Column: Qida və içkilərin çeşidləri
float64
Qida və içkilərin çeşidləri
NaN      23
10.00     9
5.00      6
7.00      4
8.00      3
6.00      3
9.00      3
3.00      1
Name: count, dtype: int64


Column: Qida və içkilərin keyfiyyəti
float64
Qida və içkilərin keyfiyyəti
NaN      23
10.00    11
9.00      6
5.00      4
7.00      4
6.00      2
8.00      1
1.00      1
Name: count, dtype: int64


Column: Qida və içkilərin qiyməti
float64
Qida və içkilərin qiyməti
NaN      23
5.00      5
10.00     5
8.00      4
6.00      4
7.00      3
3.00      2
9.00      2
1.00      2
4.00      1
2.00      1
Name: count, dtype: int64


Column: Stadion ərazisindəki fanşopdan klubun məhsullarını almısınızmı?
str
Stadion ərazisindəki fanşopdan klubun məhsullarını almısınızmı?
Xeyr    43
Bəli     9
Name: count, dtype: int64


Column: Oyun zamanı satışda olan klubun məhsullarına nə qədər pul xərcləmisiniz?
float64
Oyun zamanı satışda olan klubun məhsullarına nə qədər pul xərcləmisiniz?
NaN      44
5.00      2
10.00     1
2.00      1
45.00     1
30.00     1
85.00     1
40.00     1
Name: count, dtype: int64


Column: Satış məntəqələrinin əlçatan olması 2
float64
Satış məntəqələrinin əlçatan olması 2
NaN      43
10.00     6
8.00      1
7.00      1
5.00      1
Name: count, dtype: int64


Column: Məhsulların çeşidləri
float64
Məhsulların çeşidləri
NaN      43
10.00     5
5.00      2
6.00      1
3.00      1
Name: count, dtype: int64


Column: Məhsulların keyfiyyəti
float64
Məhsulların keyfiyyəti
NaN      43
10.00     6
8.00      2
6.00      1
Name: count, dtype: int64


Column: Bilet alma prosesini necə qiymətləndirirsiniz?
int64
Bilet alma prosesini necə qiymətləndirirsiniz?
10    31
8      8
9      5
7      5
5      2
3      1
Name: count, dtype: int64


Column: Bilet yoxlayan əməkdaşların işini necə qiymətləndirirsiniz?
int64
Bilet yoxlayan əməkdaşların işini necə qiymətləndirirsiniz?
10    26
8      8
9      8
7      5
5      2
4      2
3      1
Name: count, dtype: int64


Column: Təhlükəsizlik xidmətinin işini necə qiymətləndirirsiniz?
int64
Təhlükəsizlik xidmətinin işini necə qiymətləndirirsiniz?
10    30
8     11
9      5
7      3
6      2
5      1
Name: count, dtype: int64


Column: Könüllülərin işini necə qiymətləndirirsiniz? (istiqamətin göstərilməsi, sualların cavablandırılması və s.)
int64
Könüllülərin işini necə qiymətləndirirsiniz? (istiqamətin göstərilməsi, sualların cavablandırılması və s.)
10    33
8      5
9      3
6      3
5      3
2      2
7      1
1      1
4      1
Name: count, dtype: int64


Column: Tribunaların təmizliyini necə qiymətləndirirsiniz?
int64
Tribunaların təmizliyini necə qiymətləndirirsiniz?
10    30
9      7
5      5
8      4
3      2
6      1
1      1
2      1
7      1
Name: count, dtype: int64


Column: Tualetlərin təmizliyini necə qiymətləndirirsiniz?
float64
Tualetlərin təmizliyini necə qiymətləndirirsiniz?
10.00    20
5.00      9
9.00      6
8.00      6
7.00      5
6.00      3
NaN       1
3.00      1
1.00      1
Name: count, dtype: int64


Column: Stadionda olan ab-havanı necə qiymətləndirirsiniz?
int64
Stadionda olan ab-havanı necə qiymətləndirirsiniz?
10    42
8      5
5      2
9      2
3      1
Name: count, dtype: int64


Column: Ümumi oyunun təşkilini necə qiymətləndirirsiniz?
int64
Ümumi oyunun təşkilini necə qiymətləndirirsiniz?
10    21
8     11
9      7
7      5
6      4
5      3
3      1
Name: count, dtype: int64


Column: Klubun faəliyyətini necə dəyərləndirirsiniz?
int64
Klubun faəliyyətini necə dəyərləndirirsiniz?
10    23
8     11
7      5
5      5
9      4
6      2
4      1
3      1
Name: count, dtype: int64


Column: Sponsorun dəstəyini necə dəyərləndirirsiniz?
int64
Sponsorun dəstəyini necə dəyərləndirirsiniz?
10    40
9      4
8      3
5      2
7      1
6      1
3      1
Name: count, dtype: int64


Column: Stadionda neçə sponsor reklamı gördünüz?
Int64
Stadionda neçə sponsor reklamı gördünüz?
1    30
0    11
2     8
3     3
Name: count, dtype: Int64


Column: Bunlar hansılardır?
str
Bunlar hansılardır?
HUNER GROUP                                   29
NaN                                           11
Tovuz Su, HUNER GROUP                          3
HUNER GROUP, Tovuz Su                          2
HUNER GROUP, Tovuz Mall                        2
HUNER GROUP, Tovuz Su, FİF                     1
HUNER GROUP, Oyal, Böyük Qışlaq Su             1
HUNER GROUP, Ada Store                         1
Az Group, HUNER GROUP, Kapital Bank Plakat     1
Böyük Qışlaq Su                                1
Name: count, dtype: int64


Column: Son oyundakı təcrübənizə əsasən, Turan Tovuz PFK-nın növbəti oyunlarını stadionda izləmək istəyərdiniz?
str
Son oyundakı təcrübənizə əsasən, Turan Tovuz PFK-nın növbəti oyunlarını stadionda izləmək istəyərdiniz?
Bəli    46
Xeyr     6
Name: count, dtype: int64


Column: Son oyundakı təcrübənizə əsasən, dostlarınıza Turan Tovuz PFK-nın oyunlarını stadionda izləməyi tövsiyə edərsiniz?
str
Son oyundakı təcrübənizə əsasən, dostlarınıza Turan Tovuz PFK-nın oyunlarını stadionda izləməyi tövsiyə edərsiniz?
Bəli    47
Xeyr     5
Name: count, dtype: int64


Column: Ad, soyad
str
Ad, soyad
Hüseynov Əsgər         2
Tural İmanov           1
Rüstəm Zeynalov        1
Gülnarə Qədirova       1
Sameddin qumasov       1
Rəşad Şrinov           1
İsmixan Adıgözəlöv     1
Şahin Kərimov          1
Fərid Əliyev           1
Elsəvər Cəfərov        1
Nübar Süleymanova      1
Ülviyyə Mustafayeva    1
Rafiq Abbasov          1
Gündüz Rzayev          1
Dərya Məsimov          1
Elton Nuriyev          1
Polad Tağıyev          1
Vəliyev Tural          1
Eltay Aslanov          1
Əlyar Mahmudov         1
Aliyev Amil            1
Arif Abbasov           1
Seymır Sarıyev         1
Amil Mehdiyev          1
Ayaz Məmmədov          1
Rövlan Rəsulzadə       1
Azad İsmayılov         1
Samir Həsənov          1
Çingiz Qarayev         1
MirAsif Seyidov        1
Hüseynov Ramil         1
Aliyev Ramal           1
Elmar Ələsgərov        1
Eldəniz Ələkbərov      1
Namiq Bayramov         1
Samir Əsgərov          1
Anar Nagiyev           1
Elxan Hacıyev          1
Ayaz Teymurov          1
Tofiq Salmanov         1
Elşən Namazov          1
Aqil Əliyev            1
Samir Sarıyev          1
Suleyman Abdullayev    1
Xəyal Əşrəfli          1
Sabir Mirzəyiv         1
Tağıyev Vidadi         1
Vahid Əhmədov          1
Yelmar Alızadə         1
Ruslan Qasımov         1
Həsənov Vüqar          1
Name: count, dtype: int64


Column: Cins
str
Cins
Kişi     49
Qadın     3
Name: count, dtype: int64


Column: Yaşınız
Int64
Yaşınız
34    4
40    4
37    3
30    3
46    3
35    3
39    3
43    3
33    2
45    2
25    2
36    2
38    2
28    2
29    2
42    1
19    1
16    1
57    1
22    1
23    1
56    1
55    1
27    1
60    1
71    1
24    1
Name: count, dtype: Int64


Column: Məşğuliyyət
str
Məşğuliyyət
İşləyirəm           33
İşsizəm             12
Təqaüdçü             3
USTA                 1
Tələbə               1
Məktəbli             1
Avtomobil ustasi     1
Name: count, dtype: int64


Column: Ailə vəziyyəti
str
Ailə vəziyyəti
Evli     36
Subay    16
Name: count, dtype: int64


Column: Turan Tovuz PFK-nın fəaliyyəti ilə bağlı məlumat almaq istəyirsinizmi?
str
Turan Tovuz PFK-nın fəaliyyəti ilə bağlı məlumat almaq istəyirsinizmi?
Bəli    48
Xeyr     4
Name: count, dtype: int64


Column: Qeydlər
str
Qeydlər
Şərh yoxdur                                                                                                                              36
Yaşasın Tovuz                                                                                                                             1
NISALLAH TURUN KULUBUNU AVROPADA GORUM.                                                                                                   1
Suni ot örtüyü təbii ot örtüyü ilə əvəzlənsə əla olar                                                                                     1
Şəhid qardaşıdı                                                                                                                           1
Avropaya getsinlər satdion ot örtüyü təbii olsun                                                                                          1
Oyunçuları dəyişik.                                                                                                                       1
Sponsor reklamları sayını dəqiqləşdir                                                                                                     1
Mikrafonu düzəltmək kalonkalarını düzəltmək.                                                                                              1
Komandamıza uğurlar arzu edirem\n                                                                                                         1
Yoxdu                                                                                                                                     1
Klub hücum futbolu oynamır. qol vuru müdafiədə oturu                                                                                      1
Sadəc oyunlarını düzəltsinlər düzgün oyunasınlar. Qələbə lazımdı                                                                          1
Güclü komandayla yaxşı oynayır zəyif komandalara uduzur. Arashı bəyənmirəm deyir yaxşı oyunçu deyil. Ot örtüyünü dəyişlsə yaxşı olar.     1
Ailə üçün xüsusi vip olsa yaxşı olar ailəmizdə gələ bilər                                                                                 1
Hakim haksızlığı. Çəkliş pisdi deyir. Hakim haksızlığı var Turan Tovuza                                                                   1
Zədəlilər qayıtsa avropaya getmək istəyir.Turan Tovuza görə nəvəsinə Turan adı qoyub                                                      1
Name: count, dtype: int64


Column: Harada yaşayırsınız, oyunu izləməyə haradan gəlmisiniz? rayon/kəndin adını qeyd edin
str
Harada yaşayırsınız, oyunu izləməyə haradan gəlmisiniz? rayon/kəndin adını qeyd edin
Tovuz şəhəri            17
Qeyd olunmayıb          15
Aşağı Quşçu kəndi        3
Bozalqanlı kəndi         3
Düz Cırdaxan kəndi       2
Qovlar kəndi             2
Əsrik Cırdaxan kəndi     2
Azaflı kəndi             1
Əlimərdanlı kəndi        1
Cəlilli kəndi            1
Köhnəqala kəndi          1
Alakol kəndi             1
Bakı şəhəri              1
Əyyublu kəndi            1
Xatınlı kəndi            1
Name: count, dtype: int64


Column: Məhsulların qiyməti
float64
Məhsulların qiyməti
NaN      48
10.00     2
8.00      1
5.00      1
Name: count, dtype: int64

In [40]:
df['Stadionda son izlədiyiniz oyunu sizinlə neçə nəfər gəlib?'].apply(pd.to_numeric, errors='coerce')
df['Stadionda son izlədiyiniz oyunu sizinlə neçə nəfər gəlib?'] = df['Stadionda son izlədiyiniz oyunu sizinlə neçə nəfər gəlib?'].astype('Int64')

In [41]:
df.head()

,Timestamp,Turan Tovuz PFK-nın oyunlarını hansı tezlikdə izləyirsiniz?,Hansı səbəbdən oyunları tez tez izləmirsiniz?,Oyunları əsasən necə izləyirsiniz?,Oyunları hansı səbəbdən stadionda izləmirsiniz?,Oyun barədə məlumatı haradan əldə etmisiniz?,Bileti haradan almısınız?,Stadiona getmək üçün hansı vasitədən istifadə etmisiniz?,Stadionda son izlədiyiniz oyunu sizinlə neçə nəfər gəlib?,"Stadionda son izlədiyiniz oyunu sizinlə gələnlərin arasında uşaq var idi? bir neçə uşaq gəlmişdirsə, sayı ""digər"" bölməsində qeyd edə bilərsiniz","Sizcə, oyuna ailənizlə gəlmək üçün şərait uyğundurmu?",Xahiş edirik stadiona gedərkən üzləşdiyiniz problemləri qeyd edin:,Xahiş edirik stadionda üzləşdiyiniz problemləri qeyd edin:,Xahiş edirik stadiondan çıxarkən üzləşdiyiniz problemləri qeyd edin:,Stadion ərazisində satışda olan qida və içkilər almısınızmı?,Oyun zamanı satışda olan qida və içkilərə ortalama nə qədər pul xərcləmisiniz? məbləğ(AZN),Satış məntəqələrinin əlçatan olması,Qida və içkilərin çeşidləri,Qida və içkilərin keyfiyyəti,Qida və içkilərin qiyməti,Stadion ərazisindəki fanşopdan klubun məhsullarını almısınızmı?,Oyun zamanı satışda olan klubun məhsullarına nə qədər pul xərcləmisiniz?,Satış məntəqələrinin əlçatan olması 2,Məhsulların çeşidləri,Məhsulların keyfiyyəti,Bilet alma prosesini necə qiymətləndirirsiniz?,Bilet yoxlayan əməkdaşların işini necə qiymətləndirirsiniz?,Təhlükəsizlik xidmətinin işini necə qiymətləndirirsiniz?,"Könüllülərin işini necə qiymətləndirirsiniz? (istiqamətin göstərilməsi, sualların cavablandırılması və s.)",Tribunaların təmizliyini necə qiymətləndirirsiniz?,Tualetlərin təmizliyini necə qiymətləndirirsiniz?,Stadionda olan ab-havanı necə qiymətləndirirsiniz?,Ümumi oyunun təşkilini necə qiymətləndirirsiniz?,Klubun faəliyyətini necə dəyərləndirirsiniz?,Sponsorun dəstəyini necə dəyərləndirirsiniz?,Stadionda neçə sponsor reklamı gördünüz?,Bunlar hansılardır?,"Son oyundakı təcrübənizə əsasən, Turan Tovuz PFK-nın növbəti oyunlarını stadionda izləmək istəyərdiniz?","Son oyundakı təcrübənizə əsasən, dostlarınıza Turan Tovuz PFK-nın oyunlarını stadionda izləməyi tövsiyə edərsiniz?","Ad, soyad",Cins,Yaşınız,Məşğuliyyət,Ailə vəziyyəti,Turan Tovuz PFK-nın fəaliyyəti ilə bağlı məlumat almaq istəyirsinizmi?,Qeydlər,"Harada yaşayırsınız, oyunu izləməyə haradan gəlmisiniz? rayon/kəndin adını qeyd edin",Məhsulların qiyməti
0,2025-03-19 15:47:08.896,Hər oyununu izləyirəm,Qeyd olunmayıb,Stadionda baxıram,Qeyd olunmayıb,Sosial media kanallarından,Stadionun kassasından,Piyada,2,Xeyr,Bəli,Qarşı tribunanın üstünün bağlı olması,Heç bir problemlə üzləşmədim,Heç bir problemlə üzləşmədim,Bəli,1.00,10.00,5.00,5.00,5.00,Xeyr,NaN,NaN,NaN,NaN,10,7,10,9,10,10.00,10,6,10,10,1,HUNER GROUP,Bəli,Bəli,Tural İmanov,Kişi,37,İşləyirəm,Evli,Bəli,Şərh yoxdur,Tovuz şəhəri,NaN
1,2025-03-18 12:57:01.184,Hər oyununu izləyirəm,Qeyd olunmayıb,Stadionda baxıram,Qeyd olunmayıb,Şəhərdə yerləşən posterlərdən,Stadionun kassasından,Piyada,12,Xeyr,Bəli,Heç bir problemlə üzləşmədim,Heç bir problemlə üzləşmədim,Heç bir problemlə üzləşmədim,Bəli,1.00,10.00,10.00,10.00,10.00,Xeyr,NaN,NaN,NaN,NaN,10,10,10,10,10,10.00,10,10,10,10,3,"HUNER GROUP, Tovuz Su, FİF",Bəli,Bəli,Rüstəm Zeynalov,Kişi,42,İşsizəm,Evli,Bəli,Şərh yoxdur,Qeyd olunmayıb,NaN
2,2025-03-18 12:07:38.943,Hər oyununu izləyirəm,Qeyd olunmayıb,Stadionda baxıram,Qeyd olunmayıb,Tanışlardan,Dəvətnamə veriblər,Taksi,1,Bəli,Bəli,"Stadionun parkinqində yerin az olması, Heç bir...",Tütün məhsullarının istifadəsi. Smiçka çırtdam...,"Stadiondan çıxış zamanı sıxlıq olması, Heç bir...",Bəli,1.00,8.00,5.00,7.00,5.00,Bəli,10.00,8.00,5.00,8.00,10,10,10,10,10,5.00,10,10,8,10,3,"HUNER GROUP, Oyal, Böyük Qışlaq Su",Bəli,Bəli,Gülnarə Qədirova,Qadın,33,İşsizəm,Evli,Xeyr,Yaşasın Tovuz,Qeyd olunmayıb,NaN
3,2025-03-19 14:06:35.732,Hər oyununu izləyirəm,Qeyd olunmayıb,Stadionda baxıram,Qeyd olunmayıb,Sosial media kanallarından,Stadionun kassasından,İctimai nəqliyyat,8,Bəli,Bəli,Heç bir problemlə üzləşmədim,Heç bir problemlə üzləşmədim,Heç bir problemlə üzləşmədim,Bəli,2.00,1.00,8.00,10.00,3.00,Bəli,2.00,10.00,10.00,10.00,10,10,10,10,10,10.00,10,10,10,10,1,HUNER GROUP,Bəli,Bəli,Sameddin qumasov,Kişi,34,USTA,Evli,Bəli,NISALLAH TURUN KULUBUNU AVROPADA GORUM.,Azaflı kəndi,10.00
4,2025-03-17 20:44:32.298,Hər oyununu izləyirəm,Qeyd olunmayıb,Stadionda baxıram,Qeyd olunmayıb,Sosial media kanallarından,Səyyar satış məntəqəsindən,Şəxsi avtomobil,1,Bəli,Bəli,Heç bir problemlə üzləşmədim,qadın tualetinden kşilərin istifadə etməsi,Heç bir problemlə üzləşmədim,Bəli,2.00,10.00,10.00,10.00,3.00,Bəli,5.00,10.00,10.00,10.00,10,10,8,8,10,9.00,10,10,9,10,2,"HUNER GROUP, Ada Store",Bəli,Bəli,Rəşad Şrinov,Kişi,45,İşləyirəm,Evli,Bəli,Şərh yoxdur,Qeyd olunmayıb,NaN

In [42]:
df.shape

(52, 48)

In [43]:
save_processed(df, 'cleaned_survey_data.csv')

Fayl saxlanıldı: C:\Users\rashid\Desktop\fif_project\data\processed\cleaned_survey_data.csv (shape: (52, 48))